### ISSUE TITLE
Clarity Time Picker Component uses Browser Locale instead of Angular Locale

### ISSUE THREAD

**Issue by cvetkovicp97** [porscheinformatik/clarity-addons#1659] opened 2022-05-12 11:49 UTC
## Describe the bug

The Time Picker component shows either the 12h Format (AM/PM) or the 24h Format based on the browser locale (browser language) and not the angular locale.

![clarityTimeComponent12h](https://user-images.githubusercontent.com/33125120/168068252-b06bebb6-775a-468c-8f89-1ae39cddbfb4.PNG)

![clarityTimeComponent24h](https://user-images.githubusercontent.com/33125120/168068249-a9901432-2ca9-4ca6-899a-8dad2a2388b9.PNG)

## To Reproduce

Use the clrTime Input component: 
<input clrTime type="time"/>

1.  Use the clrTime component with browser locale (browser language) set to English.
2.  Use the clrTime component with browser locale (browser language) set to German.

## Expected behavior

The clrTime 12h/24h Format should be based on the Angular locale that can be dynamically changed for the app the user is currently using, and not be based on the locale that has been set in the browser.

## Versions

**App**

- Angular: 13.3.2
- Node: 14.16.0
- Clarity: 12.0.13
- Clarity-Addons: 10.5.1

**Device:**

- Type: Any
- OS: Any
- Browser: Any
- Version:

**Comment by Wallabeng** [comment] 2022-05-16 07:21
Hello @cvetkovicp97,

clrTime is not really a component it's just used to place it correctly inside the clr-date-time-container.
So what you see is a standard time picker offered by your browser, which also differs from browser to browser (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time).
And as far as I know and researched you can't modify this behaviour in the way you described it.

The only solution would be to use a dedicated time picker component from anywhere else. If this should be included in clarity-addons, needs to be discussed then, as for now no one needed it (at least not that badly :-) )

**Comment by Wallabeng** [comment] 2022-05-25 07:41
Closing this as it works as intended, please reopen if feeling differently about it.

**Closed by Wallabeng** 2022-05-25 07:41 UTC
